#!/usr/bin/env bash

function run_reg_test {
	echo "Running: "$1
	start_dir=$(pwd)
	cd $1 || return 255
	./test
	result=$?
	if [[ $result != 0 ]]; then
		echo "Regression test failed:"
		echo "    ${1}"
	fi
	cd $start_dir
	return $result
}

global_result=0

for test_dir in ./test/molecular_map_test/*; do
	run_reg_test $test_dir
	status_val=$?
	global_result=$((global_result + status_val))
done

exit $global_result
