#!/usr/bin/env bash

function run_reg_test {
	echo "Running: "$1
	start_dir=$(pwd)
	cd $1 || return 255
	./test
	result=$?
	if [[ $result != 0 ]]; then
		echo "Regression test failed:"
		echo "    ${1}"
	fi
	cd $start_dir
	return $result
}

result=0

for test_dir in ./test/molecular_map_test/*; do
	run_reg_test $test_dir
	status_val=$?
	echo "status_val val" $status_val
	result=$((result + status_val))
	echo "result val "$result
done

exit $result
